### ISSUE TITLE
ATZ/ATR description error

### ISSUE THREAD

**Issue by Botched1** [beegee-tokyo/WisBlock-API#7]
On "AT-Commands.md" it shows:

![Screenshot 2022-07-26 9 15 52 AM](https://user-images.githubusercontent.com/19985320/181028511-2e329052-c703-4f19-ab85-6154770f271b.png)

But I believe those descriptions are backwards... ATR does  the factory reset to defaults, and ATZ just does a reset.

**Comment by beegee-tokyo** [comment]
Thanks for finding this.
You are right, it is described wrong.

Planning an update soon, then it will be changed. The mistake is only in the content, the command descriptions itself are correct.

```
## ATR

This command restores all parameters to the initial default values of the module.

| Command | Input Parameter | Return Value | Return Code |
| ------- | --------------- | ------------ | ----------- |
| ATR?    | -               | -            | `OK`        |
| ATR     | -               | -            | `OK`        |

[Back](#content)    

----

## ATZ

Description: MCU reset

This command is used to trigger an MCU reset.

| Command | Input Parameter | Return Value             | Return Code |
| ------- | --------------- | ------------------------ | ----------- |
| ATZ?    | -               | `ATZ: Trig a MCU reset`   | `OK`        |
| ATZ     | -               | *No return. MCU resets.* | `OK`        |
```
