### ISSUE TITLE
[Android APP][BLE] 'The device does not have required services'

### ISSUE THREAD

**Issue by battosai30** [beegee-tokyo/WisBlock-API#8]
Hi,

When I try to configure LoRaWAN with Android + BLE link, I select the device and I get a pop-up saying 'The device does not have required services'

Any idea what could cause this ?

Phone : Xiaomi Mi Note 10
Wisblock-API :  1.1.16
Code = example 'api-test'

Regards

**Comment by beegee-tokyo** [comment]
I do not know the "BLE link" application. and I cannot find it in the Google Play store.

I am using either the [WisBlock Toolbox](https://play.google.com/store/apps/details?id=tk.giesecke.wisblock_toolbox) or the [Serial Bluetooth Terminal](https://play.google.com/store/apps/details?id=de.kai_morich.serial_bluetooth_terminal)

**Comment by battosai30** [comment]
Sorry I was not talking about an app, just using BLE as connection with RAK4631 ^^
I obviously used your app ;)

**Comment by beegee-tokyo** [comment]
😄 
Ok, clear now.
You are using the LPWAN SETUP, correct?
![image](https://user-images.githubusercontent.com/512690/181672654-19ca7c31-cc6e-48ed-a74e-ed2f8e648aa1.png)

Android WisBlock Toolbox version is latest (1.0.2)?

WisBlock API library is latest version 1.1.16?

When you installed WisBlock Toolbox, it asked several questions regarding access to storage, location, ...
Did you allow this access? If not, you might need to give acess in the Android settings for the application.

I just tried with latest versions of WisBlock Toolbox and api-test.ino and it worked.

**Comment by battosai30** [comment]
Yes for all ^^ and I just checked all dependancies to be sure too, everything is up to date.

Is it possible to think it's because of my phone model ?

**Comment by beegee-tokyo** [comment]
That is really strange.
Can you try one more test.
Can you install the [Nordic nRF Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) app and and check what services are advertised?
In nRF Connect start the scanner, you should see the WisBlock similar to this:
![image](https://user-images.githubusercontent.com/512690/181716294-b6f82bf2-0bd6-48c7-ab57-b5d33d74c198.png)
Push the connect button.
The service with the UUID 0xF0A0 is the service that is used for the LPWAN setup.
![image](https://user-images.githubusercontent.com/512690/181716513-d0eaaabb-a422-4229-a410-b43c6cf6bf0f.png)
